### ISSUE TITLE
Offizilles logo???

### ISSUE THREAD

**Issue by kr0l** [see-base/grafik#1]
seid wann ist das logo(official).svg das offizielle see-base logo? Ich wüsste nicht, dass wir dass mal abgestimmt haben oder dieses logo auch nur erwähnt wurde!

**Comment by DO1JLR** [comment]
??? 
Das sind die Dateien die in unserer privaten Cloud liegen.
Können wir natürlich hier auch löschen wenn du gegen die veröffentlichung dieser Grafik bist.
Hatten wir aber mal gesagt, dass wir das öffentlich haben wollen. (zB. Webseite, Github, Twittter, Profilbild, Flyer...)
